@startmindmap
'https://plantuml.com/mindmap-diagram


* algorithm
** 数据结构
*** 数组
**** 排序

*** 链表
**** 双指针
**** 反转链表

*** 树
**** 遍历
***** 前序遍历
***** 中序遍历
***** 后序遍历
***** 层序遍历
***** 深度优先
***** 广度优先

*** 图

*** 堆

*** 栈

*** 队列

*** Hash

*** 散列表

** 算法场景

*** 递归

*** 贪心

*** 动态规划

*** 双指针

*** 字符串处理


@endmindmap
